# Created by: Sung Gon Yi <skonmeme@gmail.com>
# $FreeBSD$

PORTNAME=	PyECLib
PORTVERSION=	1.5.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=       pyeclib-${DISTVERSION}

MAINTAINER=	skonmeme@gmail.com
COMMENT=	A simple Python interface for implementing erasure codes

LICENSE=	APACHE20

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pbr>=2.0.0:devel/py-pbr

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
