# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/net/py-amqp/Makefile 426059 2016-11-13 16:14:14Z rene $

PORTNAME=	amqp
PORTVERSION=	2.2.2
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skonmeme@gmail.com
COMMENT=	Low-level AMQP client for Python (fork of amqplib)

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}vine>=1.1.3:devel/py-vine

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
